# Generated by Django 3.1.1 on 2021-10-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mall',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mall',
            name='ubicacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
